### ISSUE TITLE
Cannot find module '@nestjs-modules/mailer' on version 1.3.14

### ISSUE THREAD

**Issue by mul14** [nest-modules/mailer#108]
I just start clean project with Nest.js. When I import `@nestjs-modules/mailer`, I got an error 
> Cannot find module '@nestjs-modules/mailer'

I use version `1.3.14`.

<img width="893" alt="Screen Shot 2020-03-31 at 12 08 15" src="https://user-images.githubusercontent.com/113989/77989403-ea105580-7348-11ea-9c82-18fe0da3f3c1.png">

When I check `node_modules/@nestjs-modules/mailer/` folder, it should have `dist` folder. But, there was none. If I downgrade to version `1.3.13`, this issue is gone.

**Comment by Oleksandra0220** [comment]
I am having the same issue, but `node_modules/@nestjs-modules/mailer/` has the `dist` folder. From package.json: `"@nestjs-modules/mailer": "^1.8.1",` Downgrading doesn't solve it.

**Comment by Ash-5** [comment]
> I am having the same issue, but `node_modules/@nestjs-modules/mailer/` has the `dist` folder. From package.json: `"@nestjs-modules/mailer": "^1.8.1",` Downgrading doesn't solve it.

@Oleksandra0220 Did you find any solution to this?
