### ISSUE TITLE
Old css-inline dependency missing, but still required

### ISSUE THREAD

**Issue by xsvetli1** [nest-modules/mailer#1119]
**Describe the bug**
I did some investigation and it seems after your commit 4f79d29, any app using handlebars will crash before even starts (same as mine is at the moment). The issue is the error message:

```
Error: Cannot find module 'css-inline'
Require stack:
- /app/backend/node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js
```

Basically, your most up-to-date version of the @nestjs-modules/mailer is after commit 4f79d29 missing dependency `css-inline` which was replaced by `@css-inline/css-inline`. However, it is not the same package! And in the `handlebars.adapter.js`, you are still trying to import the old `css-inline`.

I was able to fix it by installing `css-inline` to my app as dependency, but I believe your goal was to get rid of this old dependency, so please fix the import in handlebars.adapter.js. It may be also used somewhere else, so some deeper investigation, of some other old `css-inline` imports which were forgotten would be very helpful.

**To Reproduce**
Use the handlebar with the mailer and try to run your app.

**Expected behavior**
App using mailer with handlebar runs successfuly.

**Comment by phxgg** [comment]
Same issue with EJS.

**Comment by akrio714** [comment]
Same issue

**Comment by yjradeh** [comment]
same

**Comment by michal-worwag** [comment]
Same here

**Comment by lostation** [comment]
same here with EjsAdapter ;)

**Comment by daniloras** [comment]
same here ----- HAVE PROBLEM

**Comment by wagnersillva** [comment]
same here... Any solution? 
I'm using docker to deploy my nestjs application.

**Comment by basz** [comment]
It was fixed in latest version. Otherwise add css-inline as dependency
