### ISSUE TITLE
Error: Cannot find module '@css-inline/css-inline-linux-x64-musl'

### ISSUE THREAD

**Issue by wagnersillva** [nest-modules/mailer#1128]
I'm using Dcoker to deploy my nestjs application.

Error: 

> stock-in-cloud@0.0.1 start:prod
> node dist/main

/user/src/app/server/node_modules/@css-inline/css-inline/index.js:250
    throw loadError
    ^

Error: Cannot find module '@css-inline/css-inline-linux-x64-musl'
Require stack:
- /user/src/app/server/node_modules/@css-inline/css-inline/index.js
- /user/src/app/server/node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js

--------------------------------------------------------------------------------------------------------------------

version in use => @nestjs-modules/mailer "^1.10.3"

**Comment by cmoreira-handtevy** [comment]
Having the same issue, but only when using Node 20. Switching to node 18 seems to work for me.

**Comment by wagnersillva** [comment]
I only was install @css-inline/css-inline-linux-x64-musl and this work for me.

This is my new dockerfile:


`# Installing dependencies:

FROM node:18-alpine AS install-dependencies

RUN apk update && apk add chromium

WORKDIR /user/apps/server

COPY . .

RUN npm install --quiet --no-optional --no-fund --loglevel=error

# Adicionado temporariamente (falha na atualização de `@nestjs-modules/mailer`)
RUN npm install @css-inline/css-inline-linux-x64-musl

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
`

**Comment by josebright** [comment]
I had the same issue but fixed it with the following steps:
After docker up, I notice that the file was mounted. In your docker-compose.yml, you will need to remove or comment
# volumes:
    #   - .:/app
 
 
 Doing this and re-building and docker up it will help to fix the issue
