### ISSUE TITLE
Error: Cannot find module '@css-inline/css-inline-freebsd-x64'

### ISSUE THREAD

**Issue by krzysiek3d** [nest-modules/mailer#1146]
Error: Cannot find module '@css-inline/css-inline-freebsd-x64'

When try to install it like this: "yarn add @css-inline/css-inline-freebsd-x64" I get 

error An unexpected error occurred: "https://registry.yarnpkg.com/@css-inline%2fcss-inline-freebsd-x64: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/usr/home/public_nodejs/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

node v.20.11.1
version in use => @nestjs-modules/mailer "^1.11.2"

**Comment by krzysiek3d** [comment]
Ok I'v fixed it by reverting to older version => "@nestjs-modules/mailer": "1.10.3".

**Comment by jaqarrick** [comment]
I'm also having issues like this with `2.0.2`. I don't think reverting to older version is a good longterm solution as previous versions have security / dependabot issues.
