### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by aleksey-tk** [nest-modules/mailer#1157]
There is a critical security issue in one of the dependencies reported 3 weeks ago (#1143), a bug reported that breaks many CIs (#1131), a couple of merge requests and no reaction whatsoever from the package maintainers. 

I am considering to stop using this package in a nearest future.

**Comment by LeandroGazoli** [comment]
This is actually worrying.
and now I fear yet another severe error.

https://github.com/advisories/GHSA-8cp3-66vr-3r4c

**Comment by juandav** [comment]
✅ DONE

**Comment by Veloz-X** [comment]
@juandav It is still not resolved
