### ISSUE TITLE
Template support for plain text body

### ISSUE THREAD

**Issue by gaara4896** [nest-modules/mailer#137]
Currently, `text` is able to accept an `attachment-like object` as below, however, the file it takes in does not render with context.

```
      this._mailerService.sendMail({
        from: '"Company" <' + this._configService.get('MAIL_FROM') + '>',
        to: email, // list of receivers (separated by ,)
        subject: 'Frogotten Password',
        text: {path: __dirname + '/../../templates/plain/reset-password.hbs'},
        template: 'reset-password',
        context: {
          code: tokenModel.newPasswordToken,
          username: userFromDb.username,
          resetPasswordUrl: `honeygram://user/reset-password/${tokenModel.newPasswordToken}`,
        },
      });
```

***plain/reset-password.hbs***
```
Hi {{username}},

Below is the reset password code you had requested:

{{code}}
```

The plain text body are rendered together with `{{username}}` without replacing it to the actual username. 

I had also came to notice there is people who had successfully achieve that goal with `ejs` here: https://github.com/nodemailer/nodemailer/issues/648

Can I know if such is possible? I had also tried with ejs and ejs adapter and the context does not works as well.

**Comment by leosuncin** [comment]
Hey @gaara4896, can you provide a example repository with the issue?

**Comment by leosuncin** [comment]
To solve the problem (as you can see in the [referred issue](https://github.com/nodemailer/nodemailer/issues/648#issuecomment-240707126)) the plain text template has to be compiled and rendered before passed with the options object to `nodemailer` not the other way. As you coded `nodemailer` will read the content as plain text.

**Comment by gaara4896** [comment]
This problem is solved by manually converting the template using Handlebars and pass in the converted string into sendMail.

```
      var template = Handlebars.compile(
        readFileSync(
          __dirname + '/../../templates/plain/reset-password.hbs',
        ).toString(),
      );

      var context = {
        code: tokenModel.newPasswordToken,
        username: userFromDb.username,
        resetPasswordUrl: `app://user/reset-password/${tokenModel.newPasswordToken}`,
      };

      this._mailerService.sendMail({
        from: '"Company" <' + this._configService.get('MAIL_FROM') + '>',
        to: email,
        subject: 'Frogotten Password',
        text: template(context),
        template: 'reset-password',
        context: context,
      });
```
