### ISSUE TITLE
No exported member "EjsAdapter"

### ISSUE THREAD

**Issue by alexy4744** [nest-modules/mailer#181]
Hi, when I import EjsAdapter as shown in the example in the docs, typescript claims that is not exported.
```typescript
import { EjsAdapter, MailerModule } from "@nestjs-modules/mailer";
```
```
Module '"../node_modules/@nestjs-modules/mailer"' has no exported member 'EjsAdapter'.
```

**Comment by juandav** [comment]
You could create a separate repo where they put the example of this issue. Thank you

**Comment by alexy4744** [comment]
@juandav Here you go: https://github.com/alexy4744/-nestjs-modules-mailer

The import statement is located in the app.module file.

**Comment by juandav** [comment]
```ts
import { EjsAdapter } from "@nestjs-modules/mailer/dist/adapters/ejs.adapter";
```
