### ISSUE TITLE
Incorrect template.options documentation / types

### ISSUE THREAD

**Issue by dantman** [nest-modules/mailer#19]
The README gives the following example for template.options:
```js
template: {
  dir: __dirname + '/templates',
  adapter: new HandlebarsAdapter(), // or new PugAdapter()
  options: {
    debug: true,
    doctype: 'html',
  },
},
```

There appear to be several issues with this:

- `MailerOptions` declares `options` as `{ [name: string]: string; }`, meaning that any booleans including the `debug` in the example or the real-world `strict` become type errors
- To my understanding `options` is passed to `handlebars.compile`, which according to [this documentation](https://handlebarsjs.com/reference.html) does not appear to accept either `debug` or `doctype` options but the example is showing usage of handlebars.

**Comment by partyka95** [comment]
@dantman check 1.0.4 version
