### ISSUE TITLE
AWS SES transport with handlebars

### ISSUE THREAD

**Issue by DiogoBatista** [nest-modules/mailer#192]
Hello all,

Im having a small issue with sending emails using the aws SES transport.

this is my mailerModule configuration
```
MailerModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => ({
        transport: {
          SES: new AWS.SES({
            accessKeyId: configService.get('AWS_ACCESS_KEY'),
            secretAccessKey: configService.get('AWS_SECRET_KEY'),
            region: configService.get('AWS_REGION')
          })
        },
        defaults: {
          from: `"${configService.get("APP_NAME")}" <${configService.get(
            "FROM_EMAIL"
          )}>`,
        },
        template: {
          dir: resolve(process.cwd(), "dist", "assets", "templates"),
          adapter: new HandlebarsAdapter(),
          options: {
            strict: true,
          },
        },
      }),
      inject: [ConfigService],
    }),
```

And this is the command im running 
```
    this.mailerService.sendMail({
      to: user.email,
      from: this.configService.get("FROM_EMAIL"),
      subject: USER_MAIL_MESSAGES.USER_CREATED_SUBJECT,
      template: USER_EMAIL_TEMPLATES.USER_CREATED,
      context: {
        appName: this.configService.get("APP_NAME"),
        name: user.fullName(),
        confirmationLink: `${this.configService.get(
          "FRONTEND_URL"
        )}/en/confirm-email/${emailToken}`, 
      },
    });
```

I have handlebars and nodemailer installed as dependencies but I keep on getting this error:

```
(node:67125) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
(node:67125) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:67125) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Everything was working properly with mailgun but as soon as I configured the aws SES transport I get this error. Any idea what might be?

Thank you in advance and really nice job with the library, really enjoy it :)

**Comment by DiogoBatista** [comment]
I did a fresh installation of nestjs and did a basic template example as showed in the `samples` directory and it seems that as soon as we put the "template" key we get the error. 

```
(node:88585) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
(node:88585) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:88585) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
version:  "@nestjs-modules/mailer": "^1.5.0" 

Without templating it works fine, which is a shame because one of the big advantages of this library is the templating option

Anyone has the same error as me?

**Comment by juandav** [comment]
Can you please create a repo called "@nest-modules/mailer-192" to validate to understand more about the problem you are raising?

**Comment by yasuoyuhao** [comment]
Hey, Guest,
I also use AWS SES service, and I will use SMTP authorization for now.
![CleanShot 2021-04-13 at 15 42 54@2x](https://user-images.githubusercontent.com/17445398/114515599-1c98a200-9c6f-11eb-959e-a3a7cdd91c3d.png)

And Use SMTP with code

```
{
      transport: {
        host: 'your aws account's Server Name',
        port: 587,
        secure: false, // upgrade later with STARTTLS
        auth: {
          user: "{{Username just generated}}",
          pass: "{{Password just generated}}",
        },
      },
      defaults: {
        from: this.configService.mailerSenderFrom,
      },
      template: {
        dir: location,
        adapter: new HandlebarsAdapter(),
        options: {
          strict: true,
        },
      },
    }
```

**Comment by jlarmstrongiv** [comment]
Unfortunately, that workaround means that port 25 needs to be accessible from firewall settings, which is not always easy or possible.

**Comment by yasuoyuhao** [comment]
> Unfortunately, that workaround means that port 25 needs to be accessible from firewall settings, which is not always easy or possible.

NO, I use port 587.

**Comment by jlarmstrongiv** [comment]
Whoops, typo on my part.  Essentially, many ports are firewalled by default, and the one used by smtp is one of those.  While it’s a nice workaround, it won’t work when changing the firewall is difficult, or in my case, impossible.

**Comment by BrianKopp** [comment]
I had a similar issue, but with the Ethereal email service. I was providing the transport as:

```js
{
defaults: {
  from: `"${fromName}" <${fromEmail}>`,
},
preview: false,
transport: createTransport({
  host: 'smtp.ethereal.email',
  port: 587,
  logger: true,
  debug: true,
  auth: {
    user: configService.get('EMAIL_SMTP_USER'),
    pass: configService.get('EMAIL_SMTP_PASSWORD'),
  },
}),
template: {
  dir: join(process.cwd(), 'emails'),
  adapter: new HandlebarsAdapter(),
  options: {
    strict: true,
  },
},
};
```

Essentially, the value of the `transport` object is *itself* passed into the `nodemailer` `createTransport` on [this line](https://github.com/nest-modules/mailer/blob/6a976fcbe6cdb623a7de0c32331c7c62c71c765b/lib/mailer-transport.factory.ts#L19).

Basically, my `this.options.transport` was the *object* I had already returned by `createTransport`, rather than what is intended, which is the config that one would pass into `createTransport`.

This ultimately resulted in `nodmailer` getting a borked options value in [this line](https://github.com/nodemailer/nodemailer/blob/b75e539d71daa0b40248273e0e1d328c1e262bdd/lib/smtp-connection/index.js#L57), causing the host to be set to `localhost`.




With your case, it looks like maybe you're not passing in everything that your SES config needs. According to [these docs](https://nodemailer.com/transports/ses/#examples), it looks like you need to send an object like:

```js
{
  SES: {
    ses: foo,// an instantiated AWS SES client
    aws: bar, // ... the aws client sdk? Not sure what this is about
}
```

But in your example, you're passing straight through the object like:

```js
{
  SES: foo, // the instantiated SES client
}
```

which probably is making nodemailer consider your config as bad and replace it with default `localhost` host like it did mine.

**Comment by jcontrerasprince** [comment]
I had this issue and wanted to still try using the transporter. It looks like the object created with `new SES()` is not the one that `transport` field needed.

I tried using one of the objects created and successfully send an email:

```
MailerModule.forRootAsync({
      imports: [SmtpConfigModule],
      useFactory: async (smtpConfigService: SmtpConfigService) => ({
        transport: createTransport({
          SES: {
            ses: new SES({
              apiVersion: '2010-12-01',
              region: 'us-east-1',
              credentials: {
                accessKeyId: smtpConfigService.accessKeyId,
                secretAccessKey: smtpConfigService.secretAccessKey,
              },
            }),
            aws,
          },
        }).transporter, // this is the object that I'm sending and has the properties needed.
        template: {
          dir: __dirname + '/templates',
          adapter: new HandlebarsAdapter(),
          options: {
            strict: true,
          },
        },
      }),
      inject: [SmtpConfigService],
    }),
```

If someone wants to check it out, let us know,

**Comment by jcontrerasprince** [comment]
> 

The aws variable is coming from:
`import aws from 'aws-sdk'`

**Comment by jcontrerasprince** [comment]
> > 
> 
> where 's the "aws variable " coming from

The variable is coming from:
`import aws from 'aws-sdk'`

**Comment by kelwaffi** [comment]
> > > 
> > 
> > 
> > where 's the "aws variable " coming from
> 
> The variable is coming from: `import aws from 'aws-sdk'`

oh i see. thanks.
i was able to get mine working with this settings ,
@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
      validationSchema: Joi.object({
        AWS_ACCESS_KEY_ID: Joi.string().required(),
        AWS_SECRET_ACCESS_KEY: Joi.string().required(),
        AWS_REGION: Joi.string().required(),
        MAILTRAP_HOST: Joi.string().required(),
        MAILTRAP_PORT: Joi.number().required(),
        MAILTRAP_USERNAME: Joi.string().required(),
        MAILTRAP_PASSWORD: Joi.string().required(),
      }),
    }),
    MailerModule.forRootAsync({
      inject: [ConfigService],
      useFactory: (config: ConfigService) => {
        return {
          transport: {
            //ses configuration
            SES: new SES({
              region: 'us-east-2',
              accessKeyId: config.get<string>('AWS_ACCESS_KEY_ID'),
              secretAccessKey: config.get<string>('AWS_SECRET_ACCESS_KEY'),
            }),
          },
          defaults: {
            from: '"no-reply" <dev@tempown.com>',
          },
          preview: true,
          templates: {
            dir: join(__dirname, 'templates'),
            adapter: new HandlebarsAdapter(),
            options: {
              strict: true,
            },
          },
        };
      },
    }),
    RmqModule,
  ],
  controllers: [EmailController],
  providers: [EmailService],
})

**Comment by kelwaffi** [comment]
> > > 
> > 
> > 
> > where 's the "aws variable " coming from
> 
> The variable is coming from: `import aws from 'aws-sdk'`

after using your configuration i got this response " ses.sendRawEmail is not a function"
can u show a screenshot of how u sent templated email?

**Comment by szuttenbach** [comment]
@kelwaffi for me works such service
In app module
`
import { MailService } from 'src/mail/mail.service'

MailerModule.forRootAsync({
      useClass: MailService,
      inject: [MailService],
    }),
`

`import * as nodemailer from 'nodemailer'
import { Injectable } from '@nestjs/common'
import { SESClient } from '@aws-sdk/client-ses'
import * as aws from '@aws-sdk/client-ses'
import { ConfigService } from '@nestjs/config'
import { MailerOptions, MailerOptionsFactory } from '@nestjs-modules/mailer'
import { defaultProvider as credentialDefaultProvider } from '@aws-sdk/credential-provider-node'
import { HandlebarsAdapter } from '@nestjs-modules/mailer/dist/adapters/handlebars.adapter'

@Injectable()
export class MailService implements MailerOptionsFactory {
  constructor(private configService: ConfigService) {}

  createMailerOptions(): MailerOptions | Promise<MailerOptions> {
    const region = this.configService.get<string>('AWS_REGION')
    const from = this.configService.get<string>('EMAIL_FROM')

    const ses = new SESClient({
      region,
      credentialDefaultProvider,
    })

    const transport = nodemailer.createTransport({
      SES: { ses, aws },
    })

    return {
      transport: transport.transporter,
      defaults: {
        from,
      },
      template: {
        dir: __dirname + '/templates',
        adapter: new HandlebarsAdapter(),
        options: {
          strict: true,
        },
      },
    }
  }
}
`

**Comment by szuttenbach** [comment]
@kelwaffi for me works such service
In app module

```
import { MailService } from 'src/mail/mail.service'

MailerModule.forRootAsync({
      useClass: MailService,
      inject: [MailService],
    }),

```
and mail.service file
```
import * as nodemailer from 'nodemailer'
import { Injectable } from '@nestjs/common'
import { SESClient } from '@aws-sdk/client-ses'
import * as aws from '@aws-sdk/client-ses'
import { ConfigService } from '@nestjs/config'
import { MailerOptions, MailerOptionsFactory } from '@nestjs-modules/mailer'
import { defaultProvider as credentialDefaultProvider } from '@aws-sdk/credential-provider-node'
import { HandlebarsAdapter } from '@nestjs-modules/mailer/dist/adapters/handlebars.adapter'

@Injectable()
export class MailService implements MailerOptionsFactory {
  constructor(private configService: ConfigService) {}

  createMailerOptions(): MailerOptions | Promise<MailerOptions> {
    const region = this.configService.get<string>('AWS_REGION')
    const from = this.configService.get<string>('EMAIL_FROM')

    const ses = new SESClient({
      region,
      credentialDefaultProvider,
    })

    const transport = nodemailer.createTransport({
      SES: { ses, aws },
    })

    return {
      transport: transport.transporter,
      defaults: {
        from,
      },
      template: {
        dir: __dirname + '/templates',
        adapter: new HandlebarsAdapter(),
        options: {
          strict: true,
        },
      },
    }
  }
}
```
