### ISSUE TITLE
[Docs] Storing config as .ts or .json file and not as .js with module export

### ISSUE THREAD

**Issue by pumano** [nest-modules/mailer#2]
it's possible to import `.ts` file or `.json`, Nest is pure TypeScript framework, I suggest you to change docs to use it as `.ts` or `.json` config file instead of `.js`.

**Comment by cdiaz** [comment]
hello @pumano,
If you have a `.json` configuration file, cannot instantiate a nodemailer transport plugin.
For now we have added support for `mailerconfig.ts` file.
thanks for the suggestion.
