### ISSUE TITLE
mailerconfig support

### ISSUE THREAD

**Issue by ssi-hu-tasi-norbert** [nest-modules/mailer#20]
Hey,

Have you remove the mailerconfig.ts support for temporarily or permanently? It was a good and easy to use configuration till this release.

Thanks

tano

**Comment by IntellectProductions** [comment]
Is this what would be causing the Cannot resolve dependencies in the MailerService file?

**Comment by mfeldmeier** [comment]
@IntellectProductions if you get this error: Nest can't resolve dependencies of the MAILER_OPTIONS (?). Please make sure that the argument at index [0] is available in the MailerCoreModule context. 

then you need to import your ConfigModule like you inject your service 

```TS
export const MailerProvider = {
    imports:[ConfigModule],
    inject: [ConfigService],
    useFactory: (config: ConfigService) => ({
  here your settings
})
```
