### ISSUE TITLE
Missing export

### ISSUE THREAD

**Issue by xSirrioNx** [nest-modules/mailer#206]
`"@nestjs-modules/mailer": "^1.5.0"`
`import { HandlebarsAdapter } from '@nestjs-modules/mailer';`

Error - not exports HandlebarsAdapter

**Comment by juandav** [comment]
```ts
import { HandlebarsAdapter } from '@nestjs-modules/mailer/dist/adapters/handlebars.adapter';
```

**Comment by xSirrioNx** [comment]
> https://nest-modules.github.io/mailer/docs/mailer
> 
> ```ts
> import { HandlebarsAdapter } from '@nestjs-modules/mailer/dist/adapters/handlebars.adapter';
> ```

Oh, sorry, i am blind -_-

**Comment by xSirrioNx** [comment]
@juandav 
Hmm...
But now got
'HandlebarsAdapter is not a constructor'
Same with version 1.4.3

**Comment by juandav** [comment]
```ts
new HandlebarsAdapter({...........})
```
