### ISSUE TITLE
Nodemailer types

### ISSUE THREAD

**Issue by PVermeer** [nest-modules/mailer#241]
This module uses types from @types/nodemailer as declared in devDependencies. 

_See_:
https://github.com/nest-modules/mailer/blob/9ba25fa18d6d935764c0f2c80c122c8532fddb2b/lib/interfaces/mailer-options.interface.ts

Nodemailer is declared as a peer dependency. The documentation should state to also include this in your npm install directions e.g.:

```
npm install --save @nestjs-modules/mailer nodemailer
npm install -D @types/nodemailer
```

Better would be to just list these as dependencies so the correct version, that has been tested and works, gets installed.

**Comment by dantehemerson** [comment]
@juandav  can I take this?
