### ISSUE TITLE
Set rate limit of messages per second

### ISSUE THREAD

**Issue by boceto1** [nest-modules/mailer#243]
Is there any way to set up the rate limit of messages per second?  I read I just need to set up the property in the transport but didn't work me.
This is my code.

![image](https://user-images.githubusercontent.com/26729748/84169254-0a8e1780-aa3e-11ea-9f6e-2bfcb2797d65.png)

Thanks for your help

**Comment by squareloop1** [comment]
This could be handled by using the mailer with a queue which is provided in NestJS with the Bull package. But the docs could expand a bit better on this on how to implement the mailer with a bull queue.
