### ISSUE TITLE
[Feature request] Ability to specify more than one transport

### ISSUE THREAD

**Issue by wiktor-mazur** [nest-modules/mailer#258]
Hi,

We need our application to send e-mails using more than one transport. It would be nice to be able to specify one directly in `sendMail` method or have named transports in the config.

**Comment by wiktor-mazur** [comment]
I was just looking through sources and I think there acutally is such an option. Would you be willing to better describe it in the docs?

**Comment by peterkracik** [comment]
@wiktor-mazur I did a PR for this, which was merged yesterday
https://github.com/nest-modules/mailer/pull/804

**Comment by wiktor-mazur** [comment]
@peterkracik Cool, thanks! :)

**Comment by tungnnt309** [comment]
please give a guide about how to use this feature on the official docs
