### ISSUE TITLE
How to fix self signed certificate error ?

### ISSUE THREAD

**Issue by Leccho** [nest-modules/mailer#282]
I've been using the same config for a while and it just decided to stop working and throw this error:
```
Error: self signed certificate in certificate chain
```
I've look for a fix but found nothing conclusive.

**Comment by Leccho** [comment]
I've fixed it. With this:
```typescript
MailerModule.forRoot({
  transport: {
    host: 'smtp.example.ca',
    port: 587,
    secure: false,
    auth: {
      user: "noreply@example.com",
      pass: "example",
    },
    tls: {
      rejectUnauthorized: false // this did the trick
    }
  },
  defaults: {
    from: '<noreply@example.com>',
  },
  template: {
    dir: __dirname + '/templates',
    adapter: new HandlebarsAdapter(),
    options: {
      strict: true,
    },
  },
})
```

**Comment by arsalansofyrus12** [comment]
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import pino from 'pino';
import { ConfigModule } from '@nestjs/config';
import { JwtModule } from '@nestjs/jwt';
import { LoggerModule } from 'nestjs-pino';
import { MailService } from './mail.service';
import { EmailconfirmationService } from './emailConfirmation.service';
import { join } from 'path';
import { MailerModule } from '@nestjs-modules/mailer';
import { HandlebarsAdapter } from '@nestjs-modules/mailer/dist/adapters/handlebars.adapter';
import { BullModule } from '@nestjs/bull';
import { JwtStrategy } from './strategies/jwt.strategy';
import { LocalStrategy } from './strategies/local.strategy';
import { AuthService } from './auth.service';
import { AuthController } from './auth.controller';
import { S3Service } from '../s3/s3.service';
import { validationSchema } from '../../config/validation';
import { RefreshToken } from './entities/refresh_token.entity';
import { UserToken } from './entities/user_token.entity';
import { UserLogin } from './entities/user_login.entity';
import { User } from './entities/user.entity';
import { UserService } from '../user/user.service';
import { AuthenticationService } from './authentication.service';
import { AddRequest } from './entities/add_request.entity';
import { MemoryStoredFile, NestjsFormDataModule } from 'nestjs-form-data';
import { UserHasRoles } from './entities/user_has_roles.entity';
import { RolesHasPermissions } from './entities/role_has_permission.entity';
import { Roles } from './entities/roles.entity';
import { Permissions } from './entities/permission.entity';
import { UserPayment } from '../user/entities/user.payment.entity';
import { Visitor } from './entities/visitors.entity';

const transport = pino.transport({
  target: 'pino/file',
  options: {
    destination: process.env.LOG_DESTINATION,
    mkdir: true,
  },
});

const logger = pino(transport);
@Module({
  imports: [
    NestjsFormDataModule.config({ storage: MemoryStoredFile }),

    TypeOrmModule.forFeature([
      User,
      UserToken,
      UserLogin,
      RefreshToken,
      AddRequest,
      Roles,
      Permissions,
      RolesHasPermissions,
      UserHasRoles,
      UserPayment,
      Visitor,
    ]),
    ConfigModule.forRoot({
      isGlobal: true,
      validationSchema,
    }),
    MailerModule.forRootAsync({
      useFactory: () => {
        return {
          transport: {
            host: process.env.MAIL_HOST,
            secure: false,
            auth: {
              user: process.env.MAIL_USERNAME,
              pass: process.env.MAIL_PASSWORD,
            },

            tls: {
              rejectUnauthorized: false // This trick is working properly
            },
          },
          defaults: {
            from: process.env.MAIL_FROM,
          },
          template: {
            dir: join(__dirname, 'templates'),
            adapter: new HandlebarsAdapter(),
            options: {
              strict: true,
            },
          },
        };
      },
    }),

    BullModule.registerQueue({
      name: 'notifications',
    }),
    LoggerModule.forRoot({
      pinoHttp: {
        logger,
      },
    }),
    JwtModule.register({
      secret: process.env.JWT_SECRET,
      signOptions: { expiresIn: '3600s' },
    }),
  ],
  controllers: [AuthController],
  providers: [
    AuthService,
    LocalStrategy,
    JwtStrategy,
    EmailconfirmationService,
    MailService,
    UserService,
    AuthenticationService,
    S3Service,
  ],
})
export class AuthModule {}

**Comment by arsalansofyrus12** [comment]
const transport = pino.transport({
  target: 'pino/file',
  options: {
    destination: process.env.LOG_DESTINATION,
    mkdir: true,
  },
});

const logger = pino(transport);
@Module({
  imports: [
    NestjsFormDataModule.config({ storage: MemoryStoredFile }),

    TypeOrmModule.forFeature([
      User,
      UserToken,
      UserLogin,
      RefreshToken,
      AddRequest,
      Roles,
      Permissions,
      RolesHasPermissions,
      UserHasRoles,
      UserPayment,
      Visitor,
    ]),
    ConfigModule.forRoot({
      isGlobal: true,
      validationSchema,
    }),
    MailerModule.forRootAsync({
      useFactory: () => {
        return {
          transport: {
            host: process.env.MAIL_HOST,
            secure: false,
            auth: {
              user: process.env.MAIL_USERNAME,
              pass: process.env.MAIL_PASSWORD,
            },

            tls: {
              rejectUnauthorized: false // This trick is working properly
            },
          },
          defaults: {
            from: process.env.MAIL_FROM,
          },
          template: {
            dir: join(__dirname, 'templates'),
            adapter: new HandlebarsAdapter(),
            options: {
              strict: true,
            },
          },
        };
      },
    }),

    BullModule.registerQueue({
      name: 'notifications',
    }),
    LoggerModule.forRoot({
      pinoHttp: {
        logger,
      },
    }),
    JwtModule.register({
      secret: process.env.JWT_SECRET,
      signOptions: { expiresIn: '3600s' },
    }),
  ],
  controllers: [AuthController],
  providers: [
    AuthService,
    LocalStrategy,
    JwtStrategy,
    EmailconfirmationService,
    MailService,
    UserService,
    AuthenticationService,
    S3Service,
  ],
})
export class AuthModule {}

**Comment by zand98** [comment]
The only following setting worked for me is:   
           tls: {
              rejectUnauthorized: false
            },
            
Example:
useFactory: (configureService: ConfigureService) => {
        return {
          transport: {
            host: configureService.get('MAIL_HOST'),
            port: configureService.get('MAIL_PORT'),
            tls: {
              rejectUnauthorized: false
            },
          },
        };
      },
      
      Note nodejs and dependency versions:
      
          "@nestjs-modules/mailer": "^2.0.2",
          nodejs on my computer: v22.11.0
