### ISSUE TITLE
MjML Support?

### ISSUE THREAD

**Issue by andreimc** [nest-modules/mailer#287]
Hey guys,

Great job on this I would love to use mjml templates, is this tricky to add support for this?

https://mjml.io/

**Comment by leosuncin** [comment]
You can create your own template adapter, see the example [02-custom-template-adapter](https://github.com/nest-modules/mailer/tree/master/sample/02-custom-template-adapter)

**Comment by andreimc** [comment]
@leosuncin yeah I have :D thanks
