### ISSUE TITLE
Connection close after sending email

### ISSUE THREAD

**Issue by psr323** [nest-modules/mailer#294]
Hi,
Is there an option to close the transport connection after sending an email? Or how do I ensure that I'm not opening too many connections?

**Comment by spaquis** [comment]
Hi,
Apparently connection are not closed after sending email, after some research, it would be necessary to add a "transport.close()" after sending the email like this : 
```
transport.sendMail(mailOptions, function (error, info) {
        transport.close();
        if (error) {
            console.log(error);
        } else {
            console.log('Message sent: ' + info.message);
        }
    })
```
Can you add this ? Thanks

**Comment by psr323** [comment]
@spaquis

Is the reference to the transport object exposed in  NestJS Mailer module? If so, can you please provide a sample for that ?
