### ISSUE TITLE
Expand documentation and ISendMailOptions with attachments

### ISSUE THREAD

**Issue by Zh4rsiest** [nest-modules/mailer#30]
I managed to deal with applying attachments to the mail with the help of the nodemailer documentation but it would be really nice for newcomers to actually know about it from the nest-modules/mailer documentation.

The iSendMailOptions should be extended with something similiar to this:

    export interface ISendMailOptions extends SendMailOptions {
        to?: string;
        from?: string;
        subject?: string;
        text?: string;
        html?: string;

        template?: string;
        context?: {
            [name: string]: any;
        };
        attachments?: {
            filename: string,
            content?: Stream,
            path?: string,
            contentType: string
        }
    }

And there could be a documentation for it like in the nodemailer documentation. Other than that, love this package!

**Comment by nelsonBlack** [comment]
how did you do it , for me had to edit the node module ISendMailOptions  (not good practice ) as the code above

**Comment by Zh4rsiest** [comment]
I made this interface like how I wrote above and I imported it in my service, declared an instance of my own custom ISendMailOptions interface like this:

mail.service.ts


    ...
    import { ISendMailOptions } from '../_BUGFIX/send-mail-Options.interface';

    @Injectable()
    export class MailService {
        constructor(private readonly mailerService: MailerService) {}

        public sendApplicationMail(cF: ContactForm, lang: string): void {
            const _template =  'en-application-reply';
            const _subject = 'subject';

            const mailOptions: ISendMailOptions = {
                to: '"Example mail" <example@mail.com>',
                from: '"Full Name" <fullname@email.com>',
                subject: _subject,
                template: 'job-application-mail',
                context: {
                    name: `${cF.fullName}`,
                    email: `${cF.email}`,
                    tel: `${cF.tel}`,
                    position: `${cF.position}`,
                    message: `${cF.message}`,
                },
                attachments: {
                    filename: this.tm.removeAccents(cF.fullName) + '.' + cF.cvFileExt,
                    path: './tmp/uploads/cv/' + this.tm.removeAccents(cF.fullName) + '.' + cF.cvFileExt,
                    contentType: cF.cvFileType,
                },
            };

            this.mailerService.sendMail(mailOptions).then(() => {
                unlink('./tmp/uploads/cv/' + this.tm.removeAccents(cF.fullName) + '.' + cF.cvFileExt, () => {
                    console.log('File deleted');
                });
            }).catch( err => {
                console.log(err);
            });
        }
    }


contact-form.ts


    export class ContactForm {
        fullName: string;
        email: string;
        tel: string;
        position: string;
        message: string;
        cvFileExt?: string;
        cvFileType?: string;
    }

**Comment by nelsonBlack** [comment]
> I made this interface like how I wrote above and I imported it in my service, declared an instance of my own custom ISendMailOptions interface like this:
> 
> mail.service.ts
> 
> ```
> ...
> import { ISendMailOptions } from '../_BUGFIX/send-mail-Options.interface';
> 
> @Injectable()
> export class MailService {
>     constructor(private readonly mailerService: MailerService) {}
> 
>     public sendApplicationMail(cF: ContactForm, lang: string): void {
>         const _template =  'en-application-reply';
>         const _subject = 'subject';
> 
>         const mailOptions: ISendMailOptions = {
>             to: '"Example mail" <example@mail.com>',
>             from: '"Full Name" <fullname@email.com>',
>             subject: _subject,
>             template: 'job-application-mail',
>             context: {
>                 name: `${cF.fullName}`,
>                 email: `${cF.email}`,
>                 tel: `${cF.tel}`,
>                 position: `${cF.position}`,
>                 message: `${cF.message}`,
>             },
>             attachments: {
>                 filename: this.tm.removeAccents(cF.fullName) + '.' + cF.cvFileExt,
>                 path: './tmp/uploads/cv/' + this.tm.removeAccents(cF.fullName) + '.' + cF.cvFileExt,
>                 contentType: cF.cvFileType,
>             },
>         };
> 
>         this.mailerService.sendMail(mailOptions).then(() => {
>             unlink('./tmp/uploads/cv/' + this.tm.removeAccents(cF.fullName) + '.' + cF.cvFileExt, () => {
>                 console.log('File deleted');
>             });
>         }).catch( err => {
>             console.log(err);
>         });
>     }
> }
> ```
> 
> contact-form.ts
> 
> ```
> export class ContactForm {
>     fullName: string;
>     email: string;
>     tel: string;
>     position: string;
>     message: string;
>     cvFileExt?: string;
>     cvFileType?: string;
> }
> ```
Thanks ..much better than the way i was trying to fix it .. updating to your code above now ..thanks a bunch

**Comment by cdiaz** [comment]
@Zh4rsiest you could push a PR to add it

**Comment by shtief** [comment]
hmm, attachments are multiple. It is an array! So I prefer:

```
import { SendMailOptions } from 'nodemailer';
export interface ISendMailOptions extends SendMailOptions {
  to?: string;
  from?: string;
  subject?: string;
  text?: string;
  html?: string;
  template?: string;
  context?: {
    [name: string]: any;
  };
  attachments?: Array<{
    filename: string;
    path?: string;
    cid?: string;
  }>;
}
```

**Comment by siyandacele** [comment]
Why was the attachments option not added in the first place?

**Comment by sarawut11** [comment]
Not finished yet?

**Comment by juandav** [comment]
v1.3.4

**Comment by cazterk** [comment]
how can you implement more than one filepath?
