### ISSUE TITLE
Latest version is 1.3.22 on NPM

### ISSUE THREAD

**Issue by alpcanaydin** [nest-modules/mailer#300]
Hello 🤚,

When will you publish missing versions on NPM? As far as I saw, 1.3.22 is the latest version on NPM but 1.5.1 on GitHub.

Thanks.

**Comment by 1ur11** [comment]
@alpcanaydin there is 2 npm packages:
https://www.npmjs.com/package/@nestjs-modules/mailer - published 1.5.1
https://www.npmjs.com/package/@nest-modules/mailer  - published 1.3.22

**Comment by alpcanaydin** [comment]
@1ur11 Uppps, I totally missed that. Thanks for the response.
