### ISSUE TITLE
HTMLTOTEXT vulnerability on npmjs repo

### ISSUE THREAD

**Issue by manchuwook** [nest-modules/mailer#308]
Dependency: NPM - html-to-text@5.1.1
  RejectReasons (1)
  RejectReason:   ...
  Type:               VULNERABILITY
  Name:               SNYK-JS-HTMLTOTEXT-571464
  CVSS Score v3:      7.5
  Severity:           high
  Description Link:   [https://snyk.io/vuln/SNYK-JS-HTMLTOTEXT-571464](https://snyk.io/vuln/SNYK-JS-HTMLTOTEXT-571464)

I looked at the github repo that hosts this library and it looks like they have a workaround on the master branch, but have not pushed it to npmjs.  I would love to use the nestjs-modules/mailer library for our stuff, but I can't procure it until it gets patched.

**Comment by micalevisk** [comment]
@juandav you can close this Issue :)

![image](https://user-images.githubusercontent.com/13461315/183270797-03e42480-3c1c-441b-9732-c02be191c5df.png)
