### ISSUE TITLE
Add property "encoding" for attachments

### ISSUE THREAD

**Issue by MaartenPau** [nest-modules/mailer#336]
Support for attachments is incomplete. 
Please see the supported attributes by nodemailer and add them to this lib. 
https://nodemailer.com/message/attachments/

Most important for me: **encoding**

**Comment by DanielNetzer** [comment]
You can use this as a workaround for now
`      this.mailerService.sendMail({
        from: '',
        to: createCustomerDto.email,
        subject: '',
        html: ``,
        attachments: [
          {
            filename: 'tiptipot_reg.png',
            path: __dirname + '/images/tiptipot_reg.png',
            contentType: 'image/png',
            cid: 'tiptipot_reg',
            encoding: 'base64',
          },
        ],
      } as ISendMailOptions & { attachments: { encoding?: string } });`

**Comment by mfechner** [comment]
It seems that this was removed with update to 1.6.1:
https://github.com/nest-modules/mailer/compare/v1.6.0...v1.6.1#diff-b51ba76cd229c63d55965fb4c3203d2ea7255cf1897c1462b1ea65fd343d828bL40
