### ISSUE TITLE
Missing support for text-based fallback templates

### ISSUE THREAD

**Issue by jonasbeyer** [nest-modules/mailer#347]
As not all email clients prefer HTML-based emails, nestjs-mailer should support multiple template formats (text and HTML). If the properties `text` and `html` are both passed to nodemailer, it automatically generates a `multipart/alternative` email.

For example:
```
├── src
└── emails
    └── welcome
        ├── html.hbs
        └── text.hbs
```

**Comment by GerkinDev** [comment]
This would be super great. While the implementation is delayed to `1.7.0` roadmap as I can see, do you team have an idea about how the configuration will be like ?

For the template `welcome`:

* `welcome.html.hbs` / `welcome.text.hbs` ?
* `welcome/html.hbs` / `welcome/text.hbs` ?

I'd like to prepare my templates ahead of time waiting for this feature to be released, so knowing the expected/probable/planned files structure would help.

:beers: cheers !
