### ISSUE TITLE
Add or update Transporters Dynamically on API Calls -- Feature Request

### ISSUE THREAD

**Issue by ansaries** [nest-modules/mailer#371]
Hi there,
We are building a Multi-tenancy Application where we are giving options to a New Tenant to select and provide his SMTP options from the Front-end. We want to do something like this in our API Service:

``` 
@Injectable()
export class EmailDomainService {
  constructor ( 
    private mailerService: MailerService,
    private dynamicConfigService: DynamicConfigService 
  ) { }
  
  addOrUpdateSMTPConfig(transporter: TrasporterDto) {
    this.mailerService.addTransporter(transporter); // This can be achieved as suggest below
  }

  async sendMail(emailData) {
    const config = await this.dynamicConfigService.getTenantConfig();
    this.mailerService.sendMail({ ...emailData, transporterName: config.TransporterName})
  }
}

```
The above would need the addition of addTransporter method in MailerService as follows:
```
 public addTransporter(transporters: Map<string, Transporter>) {
    Object.keys(transporters).forEach((name) => {
      this.transporters.set(
        name,
        this.transportFactory.createTransport(
          transporters![name],
        ),
      );
      this.initTemplateAdapter(this.templateAdapter, this.transporters.get(name)!);
    });
  }
```

But there is a catch in this; since you are using an in-memory map of Transporters for managing multiple transporters that is why we can have an issue when the service restarts.

For handling this, we will have to create a memorization technique, where we check if the transporter is already configured then use existing otherwise create a new Transporter object and store it in the Transporters map. This needs to be done every time the sendEmail method is called.

Please share your thoughts, and lemme know if you are inclined towards such an implementation.

**Comment by fromage9747** [comment]
@ansaries 

Would you be able to provide information on your DynamicConfigService?

I am just trying to implement the ability where a User can send an email using their own stored SMTP credentials.

**Comment by imonirulislam** [comment]
@ansaries 
did you manage to implement this feature?
badly in need of this
