### ISSUE TITLE
[Feature request] Support multiple transports

### ISSUE THREAD

**Issue by peterpro** [nest-modules/mailer#41]
I have multiple mailgun transports (to send from several domains) and I couldn't realize how to make MailerModule to produce several transports. 

I saw description of dynamic modules on docs.nestjs, but as far as i can see - this doesn't apply to MailerModule.

**Comment by ninxxxxx** [comment]
i got this problem too

**Comment by peterpro** [comment]
> i got this problem too

@ninxxxxx I've come to workaround - you can use mailgun.js library, it's kinda more low-level but doing its job.
