### ISSUE TITLE
Is it possible to have templates in different modules?

### ISSUE THREAD

**Issue by davidjohanssson** [nest-modules/mailer#427]
As per the docs we specify just one location for the templates

````
template: {
    dir: __dirname + '/templates',
},
````

I have many templates. I don't want all of my templates in the same folder. This is how you can do it with TypeORM entities as an example. The equivalent for templates would be something like this.

````
templates: ['dist/**/*.template{.hbs}']
````

With this you could structure your templates into different modules.

Or is this already possible, if so how?

**Comment by IAL32** [comment]
Exactly the same problem.

I would like to be able to organize my templates in a different way, such as;

```
- views
- - user
- - - welcome.ejs
- - product
- - - new-product.ejs
- header.ejs
- footer.ejs
```

**Comment by KerryRitter** [comment]
Same request here. Does anyone on the project know if this is reasonably possible? I can work on a PR.
