### ISSUE TITLE
Upgrade preview-email to 3.0.0 in order to fix two big vulnerability issues

### ISSUE THREAD

**Issue by SirMishaa** [nest-modules/mailer#461]
Hello ! 

Already thank you for your work, it's a great job. 

I would like to use the module in my job, but it is vulnerable to two big vulnerabilities present in the ``preview-email@2.0.2`` library, so is it possible to update it? 

Vulnerability link : https://snyk.io/test/npm/@nestjs-modules/mailer/1.5.1?utm_medium=referral&utm_source=yarn&utm_campaign=snyk-widget

With best regards,

**Comment by vtrphan** [comment]
i see that preview mail had been updated in package.json but why has this package not been published to npm yet !?
