### ISSUE TITLE
upcoming npm release?

### ISSUE THREAD

**Issue by christoph-findling** [nest-modules/mailer#484]
hi, when can we expect a new npm release? we are looking forward to [this](https://github.com/nest-modules/mailer/pull/238/files) particular update. thanks!

**Comment by skozer** [comment]
+1

Looking forward to this change: https://github.com/nest-modules/mailer/pull/360

**Comment by LaoVang** [comment]
+1

**Comment by christiaan-dockbite** [comment]
+1

**Comment by Artimunor** [comment]
awaiting a new release of the npm package too, especially since it should fix 2 major security issues
