### ISSUE TITLE
cannot find name 'HandlebarsAdapter'

### ISSUE THREAD

**Issue by eric-sison** [nest-modules/mailer#525]
I am unable to use handlebars for sending email with templates. 

My code snippet: 

`import {MailerModule, HandlebarsAdapter} from '@nestjs-modules/mailer';

@Module({
    imports: [
      MailerModule.forRootAsync({
       useFactory: () => ({
        transport: {
          name: process.env.EMAIL_DOMAIN,
          host: process.env.SMTP_HOST,
          port: process.env.SMTP_PORT,
          secure: true,
          auth: {
            user: process.env.USER_EMAIL,
            pass: process.env.USER_PASS,
          },
          template: {
            dir: process.cwd() + '/template/',
            adapter: new HandlebarsAdapter(), // or new PugAdapter()
            options: {
              strict: true,
            },
          },
        },
      }),
    }),
    ]
})
`

in my package.json:
"@nestjs-modules/mailer": "^1.5.1",
"handlebars": "^4.7.7",
"nodemailer": "^6.4.18",

**Comment by stvvt** [comment]
See https://github.com/nest-modules/mailer/issues/206
