### ISSUE TITLE
I would really like to use nodemailer-html-to-text nodemailer plugin, is this possible? [question]

### ISSUE THREAD

**Issue by isaackearl** [nest-modules/mailer#547]
nodemailer-html-to-text is a great nodemailer plugin because it automatically created a text version of your html if you leave the text properly blank.   I've been trying to figure out if there is a way to apply this plugin through my configuration, and I don't see anywhere to do it.  Wondering if anybody can point me in a good direction for html to text conversion when using the nestjs mailer package.

https://github.com/andris9/nodemailer-html-to-text

Thanks.

**Comment by aguirrel** [comment]
It could be great! I try to use this plugin but I can't. Were you hable to do that?

**Comment by isaackearl** [comment]
It's been a long time since I worked on this project and I don't remember.  Sorry
