### ISSUE TITLE
Update version in npm package

### ISSUE THREAD

**Issue by shtief** [nest-modules/mailer#552]
Hi, when do you plan to update the version to 1.6 here?
https://www.npmjs.com/package/@nest-modules/mailer
Would be great! Thank you!

**Comment by travenin** [comment]
Please use package [`@nestjs-modules/mailer`](https://www.npmjs.com/package/@nestjs-modules/mailer), it was updated to 1.6.0. Package @**nest**-modules/mailer is deprecated.

**Comment by shtief** [comment]
Ah ok, thank you!
