### ISSUE TITLE
Cannot destructure property 'templateName' of precompile

### ISSUE THREAD

**Issue by twigs67** [nest-modules/mailer#559]
Hello,

I'm getting this error:
{"statusCode":502,"message":"Cannot destructure property 'templateName' of 'precompile(...)' as it is undefined."}

but only on production. I can't recreate it locally. Any idea what is causing this?

Thanks

**Comment by twigs67** [comment]
I turned off strict mode and it's still happening 
```
     template: {
        dir: process.cwd() + '/templates/',
        adapter: new HandlebarsAdapter(), // or new PugAdapter()
        options: {
          strict: false,
        },
      },
```

**Comment by danilkrivoshey** [comment]
@twigs67 the mail template must start with './index' I'm using 1.6.0.

Example:
this.mailerService.sendMail({
      to: 'test@mail.com',
      from: `Test<${mail.defaults.from}>`,
      subject: 'test email',
      template: `./test`,
    })

**Comment by twigs67** [comment]
@danilkrivoshey thanks for this. This worked. It's weird that this works locally and in QA, but not in production.

**Comment by Subalee** [comment]
This didn't work for me unfortunately, I had to do this and also copy the assets into dist using `nest-cli.json`
check my comment in other [issue](https://github.com/nest-modules/mailer/issues/570#issuecomment-925927135)

**Comment by Burane** [comment]
> How to handle this kind of error when building node app from docker??

same problem

**Comment by kova1max** [comment]
Hello from 2022. Don't start template path with "./" They check in module if template starts with "./" and if true, it breaks everything. Just start with /
![image](https://user-images.githubusercontent.com/32361852/174266715-4c250f96-1f12-48da-aab4-a22036aff13e.png)

**Comment by praisegeek** [comment]
@kova1max don't just add '/' at all. That worked for me.

**Comment by ibadshaikh99** [comment]
Inside the `nest-cli.json` file, add this object:
`"compilerOptions": {
    "assets": ["common/mail/templates/**/*"],
    "watchAssets": true
  }`
  
  Inside the assets array, add your assets paths and run `npm run build` then restart the server.

**Comment by thewalimuhammad** [comment]
It works, thanks
