### ISSUE TITLE
[Feature Request] CC & BCC params on ISendMailOptions 

### ISSUE THREAD

**Issue by DonParkison** [nest-modules/mailer#58]
Shouldnt CC & BCC be standard options when sending an email?

**Comment by DonParkison** [comment]
My environment wasnt pulling in the parent SendMailOptions type. Got it working now.

**Comment by winner106** [comment]
I cannot find "bcc"?
![image](https://user-images.githubusercontent.com/50519642/218235804-ffb038fa-065c-42e9-8976-a463acb3cf7d.png)
![image](https://user-images.githubusercontent.com/50519642/218235823-4d4a07f2-b180-431b-b23e-27f339c2f87f.png)
