### ISSUE TITLE
Async Config with Configuration Service

### ISSUE THREAD

**Issue by wambowams** [nest-modules/mailer#6]
Is it possible to get the configuration from a Configuration Service instead of the .json file?

**Comment by cdiaz** [comment]
@wambowams, In the next few days we will try to adapt the module to support the asynchronous configuration, or directly from Configservice, as described [here](https://github.com/nestjs/nest/issues/530#issuecomment-415690676)

**Comment by cdiaz** [comment]
Available in v0.4.0
