### ISSUE TITLE
Is there a reason why v1.2.0 release is not on NPM/Yarn?

### ISSUE THREAD

**Issue by aizkhaj** [nest-modules/mailer#60]
I want to use `nodemailer.createTransport()` so I can implement `nodemailer-mailgun-transport` in the `transport` field inside `MailerModule` but I can't seem to be able to go forward because the current release won't support it. However, I noticed that release 1.2.0 should have the changes required for me to implement this.

Is there a reason that release is not yet on the respective package managers? Is there another way I can get these changes to make this work?

Thanks!

**Comment by juandav** [comment]
Ok, we have permission issues to improve the module, in this respect, will receive improvements in the next two weeks.

**Comment by juandav** [comment]
Release v1.3.4
