### ISSUE TITLE
Question - How to send email with custom transporter from the service?

### ISSUE THREAD

**Issue by dacxjo** [nest-modules/mailer#607]
Is there a way to invoke a smtp or custom transporter from the emailService method "sendEmail"?

**Comment by NicolasPapp94** [comment]
Same problem here, could you found a solution?

**Comment by dacxjo** [comment]
No solution for this module, i'm using the pure nodemailer library

**Comment by lehno** [comment]
Did u find a solution?

**Comment by dacxjo** [comment]
@lehno no, using this package no, I used the pure nodemailer and created a service for custom transporters

**Comment by peterkracik** [comment]
@dacxjo could you share your code? I'm trying to solve the same thing

**Comment by peterkracik** [comment]
I created a PR for adding transporters during the runtime
https://github.com/nest-modules/mailer/pull/804
