### ISSUE TITLE
EJS support?

### ISSUE THREAD

**Issue by agarbund** [nest-modules/mailer#62]
Hey. I'd be happy to add support for EJS templates. Would you be interested in such PR if I'd sent it?

**Comment by juandav** [comment]
Sure

**Comment by juandav** [comment]
Pass a PR please

**Comment by rlataguerra** [comment]
EJS template would be awesome, but would you consider something quite agnostic to the template engine ? (where you can inject the template engine your prefer)

**Comment by juandav** [comment]
PR #126
