### ISSUE TITLE
Rename the module

### ISSUE THREAD

**Issue by juandav** [nest-modules/mailer#63]
We have decided to rename the module, for permission problems in npm, we regret the percanses

**Comment by hkyq** [comment]
From `@nest-modules` to `@nestjs-modules`? 

Is anyone else having issues importing it?

```
// Works (when @nest-modules/mailer is installed)
import { } from '@nest-modules/mailer'
// Doesn't work (even when @nestjs-modules/mailer is installed)
import { } from '@nestjs-modules/mailer'
```

`node_modules/@nestjs-modules/mailer`:

```

**Comment by impranay** [comment]
This ain't working ............. do we have any fix around this.

**Comment by juandav** [comment]
I'm checking what's happening, I will fixing the module during the day

**Comment by juandav** [comment]
Release v1.3.6
