### ISSUE TITLE
Implementation demo

### ISSUE THREAD

**Issue by yanarp** [nest-modules/mailer#64]
Hi Guys, can we get a working implementation demo.

**Comment by juandav** [comment]
I will be working on improving documentation and new features for this module.

**Comment by impranay** [comment]
I have made an simple implementation project. let me know if you want to include that in your documentation.

**Comment by juandav** [comment]
you can pass a pull request, please

**Comment by impranay** [comment]
Sure thing you got it, mate !

**Comment by gimyboya** [comment]
A demo with `Bull` package is very much welcomed as well

I was looking at this in the `README` and it looked very interesting but i am wondering what's in the ` MailQueue` file.

and what's the best practices for the `mailBullConfig` file.
```
import * as path from 'path';
import { Module } from '@nestjs/common';
import { BullModule } from 'nest-bull';
import { MailerModule, HandlebarsAdapter } from '@nestjs-modules/mailer';
import { mailBullConfig } from '../../config/mail';
import { MailService } from './mail.service';
import { MailController } from './mail.controller';
import { MailQueue } from './mail.queue';

const bullModule = BullModule.forRoot(mailBullConfig);
@Module({
  imports: [
    bullModule,
    MailerModule.forRoot({
      defaults: {
        from: '"No Reply" <noreply@example.com>',
      },
      template: {
        dir: path.join(process.env.PWD, 'templates/pages'),
        adapter: new HandlebarsAdapter(),
        options: {
          strict: true,
        },
      },
      options: {
        partials: {
          dir: path.join(process.env.PWD, 'templates/partials'),
          options: {
            strict: true,
          },
        }
      }
    }),
  ],
  controllers: [MailController],
  providers: [MailService, MailQueue],
  exports: [bullModule],
})
export class MailModule {}
```

**Comment by yanarp** [comment]
@gimyboya yeah it will be good to have working implementation with partials as well. Will try to make an PR based on this, mostly by the weekend.

**Comment by squareloop1** [comment]
Any chance for a working example with a bull queue for sending mails? It is already mentioned in the docs but not really complete.
