### ISSUE TITLE
incompatible with nestjs v8

### ISSUE THREAD

**Issue by flamewow** [nest-modules/mailer#654]
` 
$ npm i @nestjs-modules/mailer

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test@0.0.1
npm ERR! Found: @nestjs/common@8.0.0
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^8.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^7.0.9" from @nestjs-modules/mailer@1.6.0
npm ERR! node_modules/@nestjs-modules/mailer
npm ERR!   @nestjs-modules/mailer@"*" from the root project
`

**Comment by r37r0m0d3l** [comment]
```bash
npm i --legacy-peer-deps
```

**Comment by nelsonBlack** [comment]
> ```shell
> npm i --legacy-peer-deps
> ```npm install --save @nestjs-modules/mailer nodemailer --legacy-peer-deps

**Comment by nelsonBlack** [comment]
`npm install --save @nestjs-modules/mailer nodemailer --legacy-peer-deps`

**Comment by victor192** [comment]
https://github.com/nest-modules/mailer/pull/685/commits/08e61f637e022111fcbb9c0239c1b3bfab1549c6

**Comment by nickreynke** [comment]
@nelsonBlack will there be a release for the changes that @victor192 mentioned?

**Comment by omsharp** [comment]
Can you, please, look into @victor192's PR?
I desperately need this update.

**Comment by faan11** [comment]
are there any updates about this?

**Comment by svanda-navisys** [comment]
We have forked this and published the built files, so If you need Nest 8 compatibility right now, you can do the same or install our fork directly with `npm install navisyscz/mailer#dist`. Just remember to change it when they release the update.

**Comment by antoineviscardi** [comment]
Do you guys have an ETA on when a patch will be released to NPM?

**Comment by antoineviscardi** [comment]
#712
