### ISSUE TITLE
Nest can't resolve dependencies of the MailerService (?). Please make sure that the argument at index [0] is available in the UserModule context

### ISSUE THREAD

**Issue by hnakao** [nest-modules/mailer#66]
I declare Mailer module in my AppModule:

```
 MailerModule.forRoot({
            transport: `smtps://${configService.get('MAIL_USER')}:${configService.get('MAIL_PASSWORD')}@${configService.get('MAIL_SMTP_HOST')}`,
            defaults: {
                from: '"test" <noreply@test.com>',
            },
            template: {
                dir: __dirname + '/templates',
                adapter: new HandlebarsAdapter(), // or new PugAdapter()
                options: {
                    strict: true,
                },
            },
        }),
```

Then in UserService:

`constructor(private readonly mailerService: MailerService) {}`

I have a problem with circular dependency but when I try to fix throw error:

`Nest can't resolve dependencies of the UserService (?). Please make sure that the argument MailerService at index [0] is available in the UserModule context.`

Any help?

**Comment by juandav** [comment]
Hi, you tried this exanple implementation https://github.com/yanarp/nestjs-mailer
