### ISSUE TITLE
configuration, templateDir cannot resolve path with node path.resolve

### ISSUE THREAD

**Issue by mtziyo** [nest-modules/mailer#7]
Not sure if this is something I am doing wrong, but I observed when I try to use path.resolve to resolve the template directory path. the following error is thrown

UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/user/Files/project/home/user/project/src/app/welcome/index.pug'

Implementation example:

.....
import { resolve } from 'path';

@Module({
....
imports: [
 MailerModule.forRoot({
           ...,
            templateDir: resolve('views/email-templates/')
        })
]
})

The reason why I am trying to use path.resolve is that I am planning to bundle the package with webpack and the paths will change.

**Comment by cdiaz** [comment]
@mtziyo, try  `templateDir: resolve('/src/views/email-templates/')`,
