### ISSUE TITLE
Could not resolve dependency

### ISSUE THREAD

**Issue by Marcel-MD** [nest-modules/mailer#712]
Hello,
When trying to `npm install @nestjs-modules/mailer`, I get this:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: juris-rest-api@0.0.1
npm ERR! Found: @nestjs/common@8.0.11
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^8.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^7.0.9" from @nestjs-modules/mailer@1.6.0
npm ERR! node_modules/@nestjs-modules/mailer
npm ERR!   @nestjs-modules/mailer@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by LoannPowell** [comment]
Same problem with the library

**Comment by antoineviscardi** [comment]
Do you guys have an ETA on when a patch will be released to NPM?

**Comment by faan11** [comment]
All i want for Christmas is this package update. Any news?

**Comment by GauravRajSharma** [comment]
Hoping for this fix to be released soon. <3

**Comment by muhammadnasr** [comment]
Why everything I try to do with nest.js is hard?
Same issue yesterday with HttpModule, the documentation steps simply didn't work!

**Comment by muhammadnasr** [comment]
For now you can use this work around
npm install --save @nestjs-modules/mailer nodemailer --legacy-peer-deps

For HttpModule I simply used plain axios 

For my next project/upgrade I will certainly use some thing like sails.js simple and to the point.
I don't know why Nest.js reminds me with legacy J2EE configuration over configuration over ...

**Comment by Papooch** [comment]
This has already been fixed, hasn't it?

**Comment by mauriciogonzaloperedosaracho** [comment]
> Por ahora, puede usar esta solución npm install --save @nestjs-modules/mailer nodemailer --legacy-peer-deps
> 
> Para HttpModule simplemente usé axios simples
> 
> Para mi próximo proyecto/actualización, ciertamente usaré algo como sails.js simple y directo. No sé por qué Nest.js me recuerda con la configuración J2EE heredada sobre la configuración sobre...

por el momento use esto y si se instalo

**Comment by leegee** [comment]
npm 9.3.1
```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @xxx/api@1.0.3
npm WARN Found: @nestjs/common@8.4.7
npm WARN node_modules/@nestjs/common
npm WARN   @nestjs/common@"^9.2.1" from the root project
npm WARN   3 more (@nestjs/core, @nestjs/platform-express, @nestjs/testing)
```

**Comment by RandyRojo** [comment]
Same problem, please update the library. 
Thank you so much

**Comment by Manujdhull** [comment]
Beacuse you are using the nest version greater than 9 or less than 6 it can not load work on above version 9
