### ISSUE TITLE
Is this package abandoned?

### ISSUE THREAD

**Issue by wereii** [nest-modules/mailer#728]
There are important fixes (and updates) pending for this package and mainly, because of this package's stale dependencies, it's hard to resolve other deps that have security vulnerabilities.

**Comment by Tam2** [comment]
I'm having the same issue loads of dependencies issues and security vulnerabilities

**Comment by andriusign** [comment]
Looks like this package is abandoned. Maybe someone can suggest a good alternative? I see quite many forks of this one.

**Comment by wereii** [comment]
I guess we will be dropping this package for nodemailer itself directly, wrapping it manually for nestjs ourselves. The usage API is almost same as far as I checked.

**Comment by cdiaz** [comment]
Hello, unfortunately I moved to other technologies and I have not been able to dedicate time to manage the repository, so we are looking for maintainers who want to take care of this.

**Comment by some-user123** [comment]
> I guess we will be dropping this package for nodemailer itself directly, wrapping it manually for nestjs ourselves.

Could you provide a link to a gist etc.?

**Comment by jinpy666** [comment]
I have the same problem

<img width="815" alt="image" src="https://user-images.githubusercontent.com/5868671/158940924-8dcbfdfb-01d8-4af6-b0bc-f45a57c474ea.png">

**Comment by batflarrow** [comment]
> There are important fixes (and updates) pending for this package and mainly, because of this package's stale dependencies, it's hard to resolve other deps that have security vulnerabilities.

Hey were you successful in wrapping up nodemailer with nests?

**Comment by sluxzer** [comment]
I like to know updates of this package
