### ISSUE TITLE
Missing attachments property in ISendMailOptions

### ISSUE THREAD

**Issue by arndwestermann** [nest-modules/mailer#731]
I yesterday I updated to v1.6.1 and I've noticed that the attachment property got removed as seen in [this commit](https://github.com/nest-modules/mailer/commit/08e61f637e022111fcbb9c0239c1b3bfab1549c6#diff-b51ba76cd229c63d55965fb4c3203d2ea7255cf1897c1462b1ea65fd343d828b). Any reason for this?

**Comment by fmichenaud** [comment]
Must be a mistake. I had to rollback since it's a breaking change "feature" but still a minor version upgrade...

**Comment by mfechner** [comment]
Any updates on this issue @fmichenaud?

**Comment by rbaumi** [comment]
Can you please realese fixed version having `attachements` property in?

**Comment by hakanonal** [comment]
Is there ETD of new release that includes this fix @fmichenaud?

**Comment by fmichenaud** [comment]
Sorry, I'm not aware of any new release yet

**Comment by morpheus-87** [comment]
Should be fixed in `1.7.0`.
