### ISSUE TITLE
Push a new version please.

### ISSUE THREAD

**Issue by derech1e** [nest-modules/mailer#755]
Can you push a newer version with the updated dependencies and stuff like that to NPM? It would be really nice to have a working template system.

Thank you!

**Comment by stephenwade** [comment]
@juandav Please take a look at this.

**Comment by derech1e** [comment]
Any updates here?

**Comment by derech1e** [comment]
For everyone who need this version with updated packages: 
https://www.npmjs.com/package/@derech1e/mailer

**Comment by thenaim** [comment]
why closed or package is no longer support?

**Comment by thenaim** [comment]
@juandav, any news on this?

**Comment by derech1e** [comment]
> why closed or package is no longer support?

Because I Published my own version with the updated packages.

https://www.npmjs.com/package/@derech1e/mailer

**Comment by thenaim** [comment]
@derech1e, It would be great if you reopen. To make the issue visible (reach out to the author).

**Comment by derech1e** [comment]
> @derech1e, It would be great if you reopen. To make the issue visible (reach out to the author).

Ok

**Comment by andriusign** [comment]
Any updates?

**Comment by lucasprogamer** [comment]
have news?

**Comment by ArtVS** [comment]
Any news?

**Comment by derech1e** [comment]
> Any news?

I'm trying to keep the project up-to-date here: https://www.npmjs.com/package/@derech1e/mailer

**Comment by juandav** [comment]
The next update date for the library is scheduled for June 18 of this year.

I will check the change that day. :)

**Comment by lucasprogamer** [comment]
> The next update date for the library is scheduled for June 18 of this year.
> 
> I will check the change that day. :)
Missing 3 days

**Comment by juandav** [comment]
v1.7.0
