### ISSUE TITLE
Cannot destructure property 'templateName' of 'precompile(...)' as it is undefined.

### ISSUE THREAD

**Issue by todbapi** [nest-modules/mailer#759]
I created a separate mail module located on src/mail/mail.module.ts
`MailerModule.forRoot({
      transport: {
        host: 'localhost',
        port: 1025,
        secure: true,
        auth: { user: 'hi', pass: 'hi' },
      },
      defaults: { from: '"Admin" <admin@localhost.com>' },
      template: {
        dir: process.cwd() + '/templates',
        adapter: new HandlebarsAdapter(),
        options: { strict: true },
      },
    })`

my template is src/mail/templates/auth/signup-success.html.hbs

this is my service
`await this.mailService.sendMail({
      to: userMail,
      subject: 'Welcome to our app',
      template: '/auth/signup-success.html',
      context: {
        name: 'MyName',
      },
    })`

I configure my nest-cli.json

`"compilerOptions": {
    "assets": ["mail/templates/**/*.hbs"],
    "watchAssets": true
  }`

I don't know what to use process.cwd() / __dirname.

I don't know what developer do here, I try 25 different combination, every-time I get this err.

I ask, how to include .hbs file that just work.

**Comment by todbapi** [comment]
You can also put your answer here https://stackoverflow.com/questions/70820997/use-handlebars-template-in-nest-js-application

**Comment by todbapi** [comment]
As I know we can't use a `/` or `.` in template. For example this is not allowed :- `mailService.sendMail({to:myMail, template:'dir/file'})` and `mailService.sendMail({to:myMail, template:'file.html'})`
This working fine :- `mailService.sendMail({to:myMail, template:'file'})`

Developer should understand that modular code is important for bigger project.
It's bad practice to place all kind of mail template in same directory. It's also cumbersome to again and again place MailerModule in different module.

It' will be best approach if a optional templateDir options provided. So we prefix a dir name on template. This will help developer create moduler code.

**Comment by morpheus-87** [comment]
This bug is already fixed by #743 , but there is no new release with this fix :see_no_evil:

**Comment by cauli** [comment]
I just published a fork of this pending `1.6.2` version as `"@cauli/mailer": "1.6.5"`, if you need a quick fix.

**Comment by juandav** [comment]
please, use v1.7.0
