### ISSUE TITLE
README: Informative message

### ISSUE THREAD

**Issue by juandav** [nest-modules/mailer#765]
The next update date for the library is scheduled for June 18 of this year.

I will check the change that day. :) 

please be patient, I would like to dedicate more time to develop new features and apply corrections, but I can't dedicate full time, your contributions are too valuable and will be taken into account for future additions.

**Comment by juandav** [comment]
https://www.npmjs.com/package/@nestjs-modules/mailer

**Comment by juandav** [comment]
version 1.7.0 has been released.

**Comment by juandav** [comment]
If you are interested in joining the organization and would like to improve the library, please leave your comments here. The idea is to address the different issues reported. Thanks

**Comment by lucianoalzugaraydc** [comment]
Now i'm updating. Thanks you!

**Comment by juandav** [comment]
version 1.7.1 has been released.

**Comment by dantehemerson** [comment]
@juandav I would like to contribute to solving issues and adding new features. Let me know how I can start.

**Comment by juandav** [comment]
The library has already been updated to the latest version.
