### ISSUE TITLE
Build fail with no implicit any

### ISSUE THREAD

**Issue by rafaelbatistamarcilio** [nest-modules/mailer#79]
Hello people,

I don't know if this was because i update the mailer module, but the following error is happening when try to run or execute the production build.

![image](https://user-images.githubusercontent.com/16135328/76684668-91bd2200-65ec-11ea-9819-42dc2d86314a.png)

If I disable the noImplicitAny flag in tsconfig.json, everything works fine.

My tsconfig.json

```
{
  "compilerOptions": {
    "module": "commonjs",
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "noImplicitAny": true,
    "noImplicitReturns": false,
    "noUnusedParameters": false,
    "paths": {
      "@atividades/*": [ "./src/academico/atividades/*", ],
      "@documentos/*": [ "./src/academico/documentos/*"],
      "@config/*": [ "./src/config/*"],
      "@utils": [ "./src/utils"]
    }
  },
  "exclude": ["node_modules", "dist"]
}
```

I note that mailer module don't have a .d.ts file, this can be the reason of the error ?

**Comment by rafaelbatistamarcilio** [comment]
I just create an index.d.ts on the @nest-modules/mailer directory and everything works fine. 

Inside the @nest-modules/mailer/dist exists some definition files. The index.d.ts file is in the wrong directory (@nest-modules/mailer/dist/index.d.ts)?

**Comment by rafaelbatistamarcilio** [comment]
Another definition error in ISendMailOptions, template option is not recognized

![image](https://user-images.githubusercontent.com/16135328/76685549-7275c300-65f3-11ea-8f1a-4719473632a7.png)

The ISendMailOptions interface is extending SendMailOptions.  It doesn't have to extend MailerSendMailOptions? 

I changed the heritage and everything works fine.

![image](https://user-images.githubusercontent.com/16135328/76685612-eb751a80-65f3-11ea-9bc3-5f407a98cdac.png)

If that changes are correct can i open an PR ?  :smiley:

**Comment by juandav** [comment]
PR please

**Comment by rafaelbatistamarcilio** [comment]
@juandav  that's my first contribution for an open source project, any tip about commit messages, branch names, etc are very welcome! Thanks o lot for the opportunity of contribute with the project.

**Comment by juandav** [comment]
thank you.
