### ISSUE TITLE
Update to Nest V9

### ISSUE THREAD

**Issue by rohanrajpal** [nest-modules/mailer#803]
**Describe the bug**
Nest V9 is released now:
https://github.com/nestjs/nest/releases/tag/v9.0.0

**To Reproduce**
1. Setup nest v9
2. Install nest modules mailer

```bash
 WARN  Issues with peer dependencies found
apps/api
├─┬ @nestjs-modules/mailer
│ ├── ✕ unmet peer @nestjs/common@"^7.0.9 || ^8.0.0": found 9.0.1
│ └── ✕ unmet peer @nestjs/core@"^7.0.9 || ^8.0.0": found 9.0.1
```

**Expected behavior**
I've tried a force install and things seem to work fine, so I guess we just have to bump up the versions

**Comment by JessJNielsen** [comment]
PR waiting for this issue: https://github.com/nest-modules/mailer/pull/802

**Comment by rohanrajpal** [comment]
Looks like the PR is merged 🎉 

Just gotta wait for a release now and things shall be good to go

**Comment by miladganjali** [comment]
I can't install this package in v9

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: notification@0.0.1
npm ERR! Found: @nestjs/common@9.0.3
npm ERR! node_modules/@nestjs/common
npm ERR!   peer @nestjs/common@"^9.0.0" from @nestjs/core@9.0.3
npm ERR!   node_modules/@nestjs/core
npm ERR!     peer @nestjs/core@"^9.0.0" from @nestjs/testing@9.0.3
npm ERR!     node_modules/@nestjs/testing
npm ERR!       dev @nestjs/testing@"^9.0.3" from the root project
npm ERR!   peer @nestjs/common@"^9.0.0" from @nestjs/testing@9.0.3
npm ERR!   node_modules/@nestjs/testing
npm ERR!     dev @nestjs/testing@"^9.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @nestjs-modules/mailer@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @nestjs/common@8.4.7
npm ERR! node_modules/@nestjs/common
npm ERR!   peer @nestjs/common@"^7.0.9 || ^8.0.0" from @nestjs-modules/mailer@1.7.1
npm ERR!   node_modules/@nestjs-modules/mailer
npm ERR!     @nestjs-modules/mailer@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
```

**Comment by olhapi** [comment]
@miladganjali just installed it today and it works just fine

**Comment by rohanrajpal** [comment]
@olhapi The last release was a month ago, just checked npm. I don't think the new changes have been incorporated into a release yet, so not sure how it worked out for you.

@juandav, I was wondering when you plan to make the next release. It would be super helpful for people looking to use this great library with v9!

**Comment by juandav** [comment]
Well, today I will release a new version with that changes.

**Comment by miladganjali** [comment]
I switched my pc still getting the same error @olhapi 

```
$ node --version
v18.6.0
$npm --version
8.13.2
$nest --version
9.0.0

$ npm install --save @nestjs-modules/mailer
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: example@0.0.1
npm ERR! Found: @nestjs/common@9.0.4
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^9.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^7.0.9 || ^8.0.0" from @nestjs-modules/mailer@1.7.1
npm ERR! node_modules/@nestjs-modules/mailer
npm ERR!   @nestjs-modules/mailer@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
```

**Comment by olhapi** [comment]
@miladganjali yeah, I can see that peer deps of mailer was not updated at that time, but I really didn't have issues installing it. Probably I got a warning message, but nestjs v9 is just came out so it's expected. I'm using yarn, maybe that's why it worked for me.

**Comment by zdev-online** [comment]
> It has not been released on the specified date due to an error detected, patience will communicate here the new version.

We are waiting, sir 😁

**Comment by florinn-fortech** [comment]
Hi,

Can you please help us with the release or give us a tentative date?

Regards,
Florin

**Comment by tutods** [comment]
I need this release too please!

**Comment by dagistan-tuncbilek** [comment]
Hi, i need this release too, please.

**Comment by chanx** [comment]
if you urgent needing this on nestjs v9, just force install this package, it working on nestjs v9.

**Comment by dagistan-tuncbilek** [comment]
> v1.8.1 has been released.

Thanks

**Comment by micalevisk** [comment]
@juandav thanks. You can close this Issue now :)

![image](https://user-images.githubusercontent.com/13461315/183270721-2b9c1634-30a6-4ac4-96e3-4a69058c43df.png)
