### ISSUE TITLE
Glob for partials not working

### ISSUE THREAD

**Issue by samimi-electronics** [nest-modules/mailer#825]
**Describe the bug**
I have set the partials and templates directory correct. The templates loads but the partials are not found. I did some debugging and found the problem to be related to the imported glob module.

**Module setup**
```
@Module({
  imports: [
    MailerModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: async (configService: ConfigService) => ({
        defaults: {
          from: configService.getOrThrow<string>('EMAIL_FROM'),
        },
        transport: {
          host: configService.getOrThrow<string>('SMTP_HOST'),
          port: configService.getOrThrow<number>('SMTP_PORT'),
          auth: {
            user: configService.getOrThrow<number>('SMTP_USER'),
            pass: configService.getOrThrow<number>('SMTP_PASS'),
          },
          secure: configService.getOrThrow<boolean>('SMTP_SECURE'),
        },
        template: {
          dir: path.join(__dirname, 'templates', 'pages'),
          adapter: new HandlebarsAdapter(),
          options: {
            strict: true,
          },
        },
        options: {
          partials: {
            dir: path.join(__dirname, 'templates', 'partials'),
            options: {
              strict: true,
            },
          },
        },
      }),
    }),
    BullModule.registerQueueAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: async (configService: ConfigService) => ({
        redis: {
          port: configService.getOrThrow<number>('REDIS_PORT'),
          host: configService.getOrThrow<string>('REDIS_HOST'),
        },
        name: configService.getOrThrow<string>('MAIL_QUEUE_NAME'),
      }),
    })
  ],
  providers: [MailService, MailProcessor],
  exports: [MailService],
})
export class MailModule {}
```

**Send mail code**
```
const { token, ...context } = job.data;
const result = await this.mailerService.sendMail({
        template: 'email-verification',
        context: {
          ...context,
          emailVerificationLink: `http://localhost:3050/auth/verify-email?token=${token}`,
        },
        subject: `Please Confirm Your Email Address`,
        to: job.data.email,
      });
```

**Error**
`Error: The partial footer could not be found`

**Directory structure**
```
src
└── mail
 │  └── templates
 │         └── pages
 │              ├── email-verification.hbs
 │         └── partials
 │               ├── header.hbs
 │               ├── footer.hbs
 └── mail.module.ts
```
**email-verification.hbs**
```
<p>Dear {{firstname}} {{lastname}},</p>
<p>Your email verification link is:</p>
<a href="{{emailVerificationLink}}">{{emailVerificationLink}}</a>
<p>Please click the link above to verify your email address.</p>
{{> footer }}
```

**Cause**
`const files = glob.sync(path.join(runtimeOptions.partials.dir, '**', '*.hbs'));` in `handlebars.adapter.js` file at `Ln 54`.
files is set to: `[]`.

**Help**
I debugged the code and when using the interactive debugger, it reads the files but at runtime nothing is returned. I don't know what the problem is. Can someone help?

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by LetrixZ** [comment]
I have the same problem.
Turns out that glob doesn't go well with Windows paths.
Changing that line will solve the problem:
`const files = glob.sync(path.join(runtimeOptions.partials.dir, '**', '*.hbs').split(path.sep).join(path.posix.sep));` 

This will 'replace' the separators from your current platform (Windows) to POSIX separators.
`.split(path.sep).join(path.posix.sep))`

**Comment by ravand1990** [comment]
I have the same problem, however @LetrixZ your workaround doesn't seem to work for me. 
When applying the `.split(path.sep).join(path.posix.sep))` i strangely get this error message:

`Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80,
  response: undefined
}
`
Looks like an untreated exception for me to be fair that defaults to `ECONNREFUSED`.
Reverting back to the original version and removing the partial gets the job done, however it would be great to have partials :)

Any other ideas on how to fix this?

**Comment by LetrixZ** [comment]
This is the patch that I applied.
```
diff --git a/node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js b/node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js
index b42eee5..df140cc 100644
--- a/node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js
+++ b/node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js
@@ -51,7 +51,7 @@ class HandlebarsAdapter {
             data: {},
         });
         if (runtimeOptions.partials) {
-            const files = glob.sync(path.join(runtimeOptions.partials.dir, '**', '*.hbs'));
+            const files = glob.sync(path.join(runtimeOptions.partials.dir, '**', '*.hbs').split(path.sep).join(path.posix.sep));
             files.forEach((file) => {
                 const { templateName, templatePath } = precompile(file, () => { }, runtimeOptions.partials);
                 const templateDir = path.relative(runtimeOptions.partials.dir, path.dirname(templatePath));
```

**Comment by ravand1990** [comment]
> This is the patch that I applied.
> 
> ```
> diff --git a/node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js b/node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js
> index b42eee5..df140cc 100644
> --- a/node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js
> +++ b/node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js
> @@ -51,7 +51,7 @@ class HandlebarsAdapter {
>              data: {},
>          });
>          if (runtimeOptions.partials) {
> -            const files = glob.sync(path.join(runtimeOptions.partials.dir, '**', '*.hbs'));
> +            const files = glob.sync(path.join(runtimeOptions.partials.dir, '**', '*.hbs').split(path.sep).join(path.posix.sep));
>              files.forEach((file) => {
>                  const { templateName, templatePath } = precompile(file, () => { }, runtimeOptions.partials);
>                  const templateDir = path.relative(runtimeOptions.partials.dir, path.dirname(templatePath));
> ```

Yes, thats exactly what i did too, strangely it tries to connect to something that i haven't provided afterwards
My module looks like this:
`        MailModule.forRootAsync({
            imports: [ConfigModule],
            inject: [ConfigService],
            useFactory: async (configService: ConfigService) => {
                const transport = configService.get('mailer.transport');
                return {
                    transport,
                    template: {
                        adapter: new HandlebarsAdapter(handlebarsHelpers,{inlineCssEnabled: true}),
                        options: {
                            strict: false,
                        },
                    },
                    options: {
                        partials: {
                            dir: paths.partialsPath,
                            options: {
                                strict: false,
                            },
                        },
                    },
                }
            },
        })`

The transport object looks like this:
`transport: {
  host: 'xxxxxx.kasserver.com',
  port: '465',
  secure: true,
  auth: { user: 'XXXXXXX', pass: 'XXXXXXX' }
}
`
As mentioned before, when i don't apply the patch and remove the partials from the hbs files the mail gets sent with no issues.

**Comment by damdafayton** [comment]
Hi,
I just saw the folks with similar problems after opening an [issue](https://github.com/nest-modules/mailer/issues/838)
Should I close it? I found a simple/temporary fix on SO.

**Comment by samimi-electronics** [comment]
Yes please, I provided detailed description to the problem. I haven't worked on a solution yet though.

**Comment by damdafayton** [comment]
OK, I am carrying my post here:

**https://github.com/nest-modules/mailer/blob/67b767a3c21d394c1a92eb0a3f94528df60763a4/lib/adapters/handlebars.adapter.ts#L76-L78

I found out that there is a problem with this part of the code due to some deficiency with the glob library. 

It returns an empty array in my windows + node setup.

I saw a solution to similar complaints in [this SO post](https://stackoverflow.com/a/72445554/15741905)

When I tried with this code, it works fine:
```
const files = glob.sync(path.join(runtimeOptions.partials.dir, '**', '*.hbs').replace(/\\/g,'/'));
```

I dont know what is the correct approach to fix it. Maybe some kind of OS check might be necessary to make it work in windows systems.

**

**Comment by morgan-wild** [comment]
Oh I'm sorry, I was talking about the versions of NX.

It worked for me with NX13 (nestJS Core ^8.0.0) before the migration to NX14 (which brings nestJS Core ^9.0.0 and newer nestjs packages).

I'm looking for the versions of   nestjs-modules/mailer to check if it's a breaking change.

**Comment by lucas-labs** [comment]
I'm also experiencing this on Windows.
Has anyone found any workaround by any chance 😊?

**Comment by LetrixZ** [comment]
> I'm also experiencing this on a Windows server. Has anyone found any workaround by any chance 😊?
Have you tried this: https://github.com/nest-modules/mailer/issues/825#issuecomment-1207471640
