### ISSUE TITLE
Bug with glob library: It doesn't compile partials in windows

### ISSUE THREAD

**Issue by damdafayton** [nest-modules/mailer#838]
https://github.com/nest-modules/mailer/blob/67b767a3c21d394c1a92eb0a3f94528df60763a4/lib/adapters/handlebars.adapter.ts#L76-L78

I found out that there is a problem with this part of the code due to some deficiency with the glob library. 

It returns an empty array in my windows + node setup.

I saw a solution to similar complaints in [this SO post](https://stackoverflow.com/a/72445554/15741905)

When I tried with this code, it works fine:
```
const files = glob.sync(path.join(runtimeOptions.partials.dir, '**', '*.hbs').replace(/\\/g,'/'));
```

I dont know what is the correct approach to fix it. Maybe some kind of OS check might be necessary to make it work in windows systems.

**Comment by Luconico** [comment]
Thanks soooo much
