### ISSUE TITLE
sendMail options errors

### ISSUE THREAD

**Issue by yanarp** [nest-modules/mailer#85]
I believe the latest version, have somewhat didn't included the sendMail configuration in the send-mail-options-interface.ts

**Comment by juandav** [comment]
what is the error

**Comment by yanarp** [comment]
`Argument of type is not assignable to parameter of type ISendMailOptions`

**Comment by day1309** [comment]
I have the same error.. searching i found it on previous issues report, but it repeat now. 
Argument of type is not assignable to parameter of type 'ISendMailOptions' #25

**Comment by yanarp** [comment]
I'm sure this is a easy fix, cause we had a stable version of this, earlier, so prolly we gonna get the stable version again

**Comment by day1309** [comment]
Yes, im sure.. I fix it updating ISendMailOptions on node_modules package but it is not the best solutions
![image](https://user-images.githubusercontent.com/34104396/77106178-73489380-69fd-11ea-8d9b-4c9b202c7416.png)

**Comment by yanarp** [comment]
Nah, that won't do for everyone isn't. Let's wait, I'm sure will get it properly via a release !

**Comment by yanarp** [comment]
Or else you can go back to v1.3.6 I'm sure it will be working fine, I have it running in my old projects.
