### ISSUE TITLE
Send mail problem with render templates using Handlebars

### ISSUE THREAD

**Issue by Xerphis** [nest-modules/mailer#902]
When I try to send at least two emails at the same time, using a different templates (diffrent in content) (with Handlebars adapter), the content for both messages is rendered always with first template. Problem occur, when template filename is the same.  The problem does not occur when I use a different adapter, such as a PUG.

Steps to reproduce:
1. Configure mailer with template HandlebarsAdapter
2. Create two, the-same-named templates (but in diffrent directories)
3. Send two messages with diffrent templates

Problem:
Problem is in "precompiled/cache" object naming in handlebars adapter. "templateName" is prepared from `path.basename` from filepath. So, if we have two templates with the same name (but in diffrent directories), we can store only one template in precompiled cache.

Resolve:
Save precompiled templates in object with other (full) name.

Versions:
 - @nestjs-modules/mailer: 1.8.1
 - nodemailer: 6.8.0

**Comment by Bioruebe** [comment]
I opened a pull request (#888) a few month ago, which fixes this problem.
