### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:587

### ISSUE THREAD

**Issue by alexedwardjones** [nest-modules/mailer#932]
**Summary**

Setting up [nodemailer with ethereal](https://nodemailer.com/about/#example) results in `Error: connect ECONNREFUSED 127.0.0.1:587`.

If I'm understanding correctly, for some reason it seems to be picking up the host as `localhost` hence the `127.0.0.1`.

This is my current setup...

**app.module.js**
```
import { MailerModule } from "@nestjs-modules/mailer";
import { Module } from "@nestjs/common";
import { EjsAdapter } from '@nestjs-modules/mailer/dist/adapters/ejs.adapter';

import { CatModule } from "./modules/cat/cat.module";
import { join, resolve } from "path";
import { createTestAccount, createTransport } from "nodemailer";

@Module({
  imports: [
    MailerModule.forRootAsync({
      useFactory: async () => {
        const testAccount = await createTestAccount();

        const transport = createTransport({
          host: testAccount.smtp.host,
          port: testAccount.smtp.port,
          secure: testAccount.smtp.secure,
          auth: {
            user: testAccount.user,
            pass: testAccount.pass,
          },
        });

        return {
          transport,
          template: {
            dir: resolve(join(__dirname, "templates")),
            adapter: new EjsAdapter(),
            options: {
              strict: true,
            },
          },
        };
      }
    }),
    CatModule,
  ],
})
export class AppModule {}
```

**cat.service.js**

```
import { MailerService } from "@nestjs-modules/mailer";
import { Injectable } from "@nestjs/common";

@Injectable()
export class CatService {
  constructor(
    private readonly mailerService: MailerService,
  ) {}
  async doSomething(): Promise<void> {
    this.mailerService
      .sendMail({
        to: [{ name: "Joe Bloggs", address: "joebloggs@test.com" }],
        subject: "Test email",
        template: 'basic',
      });
  }
}
```

**Working transport**
The strange thing is that I can tell the transport host is configured correctly. If I send an email directly using the transport when it's created in `useFactory` then it works no problem. It only seems to lose the host when using it via the `MailerModule`.

```
    MailerModule.forRootAsync({
      useFactory: async () => {
        const testAccount = await createTestAccount();

        const transport = createTransport({
          host: testAccount.smtp.host,
          port: testAccount.smtp.port,
          secure: testAccount.smtp.secure,
          auth: {
            user: testAccount.user,
            pass: testAccount.pass,
          },
        });

        const info = await transport.sendMail({
          from: '"Fred Foo 👻" <foo@example.com>',
          to: "bar@example.com, baz@example.com",
          subject: "Hello ✔",
          text: "Hello world?",
          html: "<b>Hello world?</b>",
        });
        
        console.log("Preview URL: %s", getTestMessageUrl(info));

        return {
          transport,
          template: {
            dir: resolve(join(__dirname, "templates")),
            adapter: new EjsAdapter(),
            options: {
              strict: true,
            },
          },
        };
      }
    }),
```
Am I missing something obvious?

**Comment by vancerbtw** [comment]
@alex

did you get this figured out?

**Comment by vancerbtw** [comment]
@alexedwardjones did you get this figured out?

**Comment by ershisan99** [comment]
After a couple of hours debugging I found out the hard way that you have to pass the transport config directly to the module, without createTransport()
For instance, something like this worked for me:

`import { MailerModule } from "@nestjs-modules/mailer";
import { Module } from "@nestjs/common";
import { EjsAdapter } from '@nestjs-modules/mailer/dist/adapters/ejs.adapter';

import { CatModule } from "./modules/cat/cat.module";
import { join, resolve } from "path";
import { createTestAccount} from "nodemailer";

@Module({
  imports: [
    MailerModule.forRootAsync({
      useFactory: async () => {
        const testAccount = await createTestAccount();

        return {
          transport: {
          host: testAccount.smtp.host,
          port: testAccount.smtp.port,
          secure: testAccount.smtp.secure,
          auth: {
            user: testAccount.user,
            pass: testAccount.pass,
          },
        },
          template: {
            dir: resolve(join(__dirname, "templates")),
            adapter: new EjsAdapter(),
            options: {
              strict: true,
            },
          },
        };
      }
    }),
    CatModule,
  ],
})
export class AppModule {}`

**Comment by denodaeus** [comment]
The main problem I have with this is, if it's misconfigured it crashes the server because of an UncaughtException.  Can the code be made to be a little more resilient around this?  For example, if the local snmp server isn't working for some reason, it shouldn't crash the app.

**Comment by zub0r** [comment]
> 

Same for smtp string config - you need to pass the string directly without `createTransport`

**Comment by wilsilva** [comment]
I had the same problems. I suggest to add this like a example on documentation page. WDYT?

**Comment by BlakeGardner** [comment]
@ershisan99 thanks for your solution, I was creating a custom transport and you saved me a ton of time debugging.

**Comment by BayBreezy** [comment]
Wish I came here earlier.... After hours of banging my head against this error. 
Thanks
