### ISSUE TITLE
Import error using MjmlAdapter

### ISSUE THREAD

**Issue by jaqarrick** [nest-modules/mailer#982]
**Description**

When using the `MjmlAdapter` from the mailer module I get the following error when the compile function is invoked:
```
TypeError: (0 , mjml_1.default) is not a function
```

**To Reproduce**
In my email module imports I have the following
```
    MailerModule.forRootAsync({
      useFactory: () => ({
         ...
          adapter: new MjmlAdapter('ejs', {
            inlineCssEnabled: false,
          }),
         ...
    }),
```
When I call the `mailerService.sendMail` function the error is thrown.

**Expected behavior**
The function should successfully compile mjml to html

**Suggested Solution**
I would suggest updating the import statement [here](https://github.com/nest-modules/mailer/blob/master/lib/adapters/mjml.adapter.ts#L8) to 
```typescript
import * as mjml2html from 'mjml'
```
I've recreated the adapter locally outside of the package and this solution works. 

Let me know if I'm missing something!

**Comment by bebjakub** [comment]
Hello, I'm also experiencing the same issue. 
MRE https://github.com/bebjakub/nest-mailer-mjml-test

**Comment by bebjakub** [comment]
@juandav Thank you a lot! 
When do you plan the release, pls? The last release was 3 years ago,... 
Thank you!

**Comment by bebjakub** [comment]
Hi @jaqarrick , I tested your PR, but for me works only `import mjml2html = require('mjml')` as a solution from this issue https://github.com/mjmlio/mjml/issues/2430 or https://github.com/mjmlio/mjml/issues/1387#issuecomment-441999401
How did you achieve working it with `import * as mjml2html from 'mjml'`?
Thank you!

**Comment by carlos3g** [comment]
Did you solve it? @bebjakub

**Comment by bebjakub** [comment]
@carlos3g I duplicated MjmlAdapter and imported mjml with ```import mjml2html = require('mjml');```
