### ISSUE TITLE
Mjml fails to compile in adapter when using ejs engine

### ISSUE THREAD

**Issue by jaqarrick** [nest-modules/mailer#983]
**Describe the bug**
This one's kind of an edge case, but it's worth pointing out.

If you're using the `MjmlAdapter` with the engine set to `'ejs'` and the `inlineCssEnabled` is **not set** to `false`, the `inlineCss` method in the ejs adapter [here](https://github.com/nest-modules/mailer/blob/master/lib/adapters/ejs.adapter.ts#L60) will incorrectly wrap valid mjml tags inside html tags. Because of this, the `mjml2html` function fails because the rendered string is no longer valid mjml tags. 

For example the following mjml 
```
<mjml>
  <mj-body>
     ...
   </mj-body>
</mjml>
```
is compiled to
```
<html>
   <head>
   </head>
   <body>
       <mjml>
           <mj-body>
             ...
           </mj-body>
       </mjml>
   </body>
</html
```
Therefore, the call to compile the mjml string [here](https://github.com/nest-modules/mailer/blob/master/lib/adapters/mjml.adapter.ts#L41) fails.

**To Reproduce**
1. Define your `MjmlAdapter` like so,
```
    MailerModule.forRootAsync({
      useFactory: () => ({
         ...
          adapter: new MjmlAdapter('ejs'),
         ...
    }),
```
2. Attempt to send an email or call the function that will initiate the rendering.

**Expected behavior**
No error should be thrown and mjml should compile

**Temporary Solution**
Set the `enableInlineCss` to `false` in the adapter options.

**Suggested Solution**
The `enableInlineCss` option should be hardcoded as `false` if the engine of the `MjmlAdapter` is `'ejs'`

**Comment by martinsotirov** [comment]
I can confirm that this is the only way to get mjml to work on ejs or pug. Handlebars has a completely different bug that I haven't figured out yet:

```
                this.engine = new handlebars_adapter_1.HandlebarsAdapter(others.handlebar.helper, config);
                                                                                ^
TypeError: Cannot read properties of undefined (reading 'handlebar')
```
