### ISSUE TITLE
Type declaration missing?

### ISSUE THREAD

**Issue by albiesoft** [nest-modules/mailer#99]
Getting this error since yesterday:

Try `npm install @types/nest-modules__mailer` if it exists or add a new declaration (.d.ts) file containing `declare module '@nest-modules/mailer';`
api_1    | src/users/users.service.ts(4,31): error TS7016: Could not find a declaration file for module '@nest-modules/mailer'. '/app/node_modules/@nest-modules/mailer/index.js' implicitly has an 'any' type.

**Comment by juandav** [comment]
could you comment if you already solved the error or share an example where this is presented please

**Comment by ardyfeb** [comment]
add this on package.json
```
  "main": "./dist/index.js",
  "files": [
    "./dist"
  ],
```
