### ISSUE TITLE
Update to Nest v10

### ISSUE THREAD

**Issue by rnkdsh** [nest-modules/mailer#994]
**Describe the bug**
Nest v10 is released now:
https://github.com/nestjs/nest/releases/tag/v10.0.0

**To Reproduce**
1. Setup nest v10
2. Install nest modules mailer

**Expected behavior**
I've tried a force install and things seem to work fine, so I guess we just have to bump up the versions

**Screenshots**
<img width="669" alt="Screenshot 2023-06-17 at 12 43 22 PM" src="https://github.com/nest-modules/mailer/assets/16722278/8c0fba55-2615-4724-80f0-284b48bc6717">

**Comment by GeorgeHulpoi** [comment]
+1

**Comment by Wankishh** [comment]
+1

**Comment by ramirosacruz** [comment]
+1

**Comment by juandav** [comment]
People, today I release all the changes up to date. 💯
