### ISSUE TITLE
When support nestjs version ^10.0.0 is gonna get released?

### ISSUE THREAD

**Issue by 4H1R** [nest-modules/mailer#997]
Right now i'm trying to update the nest js to version 10 but it says mailer module doesn't support nest version 10 I can see that it's supported by when it's gonna get released on npm ?

**Comment by Shchepotin** [comment]
@juandav could you please create new NPM build for apply these changes #995?

**Comment by adminha** [comment]
please update the npm package, we're stuck ...

**Comment by ahmadalfy** [comment]
If you are stuck you can replace it with `nodemailer`. Check [this](https://github.com/nest-modules/mailer/discussions/998).

**Comment by ramirosacruz** [comment]
+1

**Comment by webgene** [comment]
@juandav Please publish v1.8.2 to NPM. We are stuck.

**Comment by rnkdsh** [comment]
+1

**Comment by wilsilva** [comment]
+1

**Comment by bvedam** [comment]
+1

**Comment by slavik-pastushenko** [comment]
+1

**Comment by prakashchokalingam** [comment]
+1 @juandav

**Comment by balenaultra** [comment]
Judging by this PR https://github.com/nest-modules/mailer/pull/995, that only the dependencies was changed, I just installed the package with the `--force` and it worked for me
Can be an option for those that are stuck

**Comment by maticorv** [comment]
+1

**Comment by TS-Tino16** [comment]
+1 

For now I just used [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) in my `package.json`, perhaps this helps someone:

```JSON
"overrides": {
    "@nestjs-modules/mailer": {
      "@nestjs/common": "$@nestjs/common",
      "@nestjs/core": "$@nestjs/core"
    }
}
```

**Comment by GeorgeHulpoi** [comment]
+1 @juandav

**Comment by tmirun** [comment]
+1

**Comment by bernatsc** [comment]
+1

**Comment by saretoduncan** [comment]
+1

**Comment by leo-belanger** [comment]
Any news on this? It's been 2 weeks.

**Comment by Shchepotin** [comment]
Looks like this repo is abandoned

**Comment by Shchepotin** [comment]
@GeorgeHulpoi me too

**Comment by ggagosh** [comment]
up 🚀

**Comment by carvalhomm** [comment]
+1

**Comment by adevaraz** [comment]
Is there any news?

**Comment by ggagosh** [comment]
up 🤖

**Comment by alirezanqp** [comment]
+

**Comment by broscr** [comment]
+1

**Comment by ggagosh** [comment]
UPUP

**Comment by JonathanLoscalzo** [comment]
+100 :100: 

The workaround to execute --force works, but the issue is i don't want to force the installation

**Comment by v-angolenko** [comment]
Can't upgrade to nest 1.10.X.

**Comment by juandav** [comment]
The version 1.9.1 of the library has been released.

**Comment by dantehemerson** [comment]
@juandav Since the lib support nest 10, can we close this issue?
